### PR TITLE
dev: add name attribute to filename, name accept more characters than an...

### PR DESCRIPTION
**Pull request by hugolpz**
... id or class.

### CODE REVIEW

**Comment by hugolpz** [comment]
beep.
Submitted patch easy to integrate. Please accept it.
@mbostock @shancarter @gka

**Comment by shancarter** [comment]
Looks good to me, but I don't have write access to this repo anymore.

**Comment by gka** [comment]
me neither!

**Comment by hugolpz** [comment]
Lol. Would be good if Magic @mbostock could grant you guys these rights :D
Pretty safe move.

**Comment by mbostock** [comment]
You should both have write access now.

**Pull request merged**
